---

satellite_url: "https://satellite.example.ca/"
satellite_organization: "Default Organization"
satellite_location: "Default Location"
satellite_username: "!vault |
                     $ANSIBLE_VAULT;1.1;AES256
                     65346531313238646365313063306133386339313636643335303863666335613065323236623739
                     3836643533306535633837613162376162623462626264620a393765343861346138656637613631
                     31363563356631396663353264343164623964656562316330373333343535633531393463646365
                     3231313137376337390a663962313937623837323930613662656433666434653337663466636565
                     6530"
satellite_password: "!vault |
                     $ANSIBLE_VAULT;1.1;AES256
                     32333334376633313463343030366638343938366436633533313564386630666435336134363863
                     3962636365366132396265666435643132633633646233380a363630666634393965303165353563
                     38646665616333356336643639336339663031646132373462396631363732353262316261613263
                     3035333232303962330a643538363836306635376462363937616434326163656266396338346165
                     3863"
satellite_validate_certs: false
