$ANSIBLE_VAULT;1.1;AES256
36633966613730663134656366333362646463303036336432383832313637633266636138643838
3938633737623866663433333162323835616331363837370a353839353431656233623539333539
30653563633534616162663139346231333839636665663834353932653065393564353063366361
6664616338666263370a366265393932623764353031373263303266306439643063386262356632
39636264646435346662616133613637386465326436386636323963613835313535353632623664
62653736366332303863653237663662333037376134613166643364616638643235356666376339
39306135393166623130656263633837316138386532656234666437323037326632353930626261
62616430613166613266373036613837366437613963666539323434616263633863616265333964
66333861643634323334313439663339643965306138333639363735653036376336656331663362
61643833393566353763376164336431316430653261326535393163626437626464633565666231
32353139656535353135613933633064366537363963646162663362663131356236663130633465
61623762333032636665666132633366396564316130613361363064316638386332393530386166
36313063636638333631353038663633343130333666346164346438336466323931643364633962
36343239383333323135333765663561653966316266313833613361646330363365323865313265
34306638383235376132643731323236363733656464396236653638633635326563666161386238
30313330383563383734
